--insert into addresses (street, area, city, state, pincode) values ('No. 38/3, arumugam circle', 'Basavanagudi', 'Bangalore', 'KA', '560004');
--
--insert into addresses (street, area, city, state, pincode) values ('Bull Temple Road, No 100/1, Maruthi Krupa', 'Basavanagudi', 'Bangalore', 'KA', '560004');
--
--insert into suppliers (name) values ('KH Associates Toys');
--
--insert into supplier_addresses (supplier_id, address_id) values (1, 12);
--
--insert into bank_accounts (name, branch, swift_code, account_number, iban, other_details) values ('ICICI Bank', 'Chamrajpet', 'ICIC0006254', '1234567890', '560229009', 'Ph: 080 3366 7777');
--
--insert into bank_account_addresses (bank_account_id, address_id) values (1, 11);
--
--insert into supplier_bank_accounts (supplier_id, bank_account_id) values (1, 1);