--insert into addresses (street, area, city, state, pincode) values ('#19, First Floor, 10th B Main 27th Cross', 'Third Block - Jayanagar', 'Bangalore', 'KA', '560011');
--
--insert into aishwarya_addresses (address_id, start_date, end_date) values (23, NOW(), '2050-01-01')
--
--insert into addresses (street, area, city, state, pincode) values ('Nr.429/31, 4th Block#Ram krishna Building', '30th Cross Jayanagar West', 'Bangalore', 'KA', '560011');
--
--insert into bank_accounts (name, branch, swift_code, account_number, iban, other_details) values ('Union Bank of India', 'Jayanagar West', 'UNION006254', '1234567890', '560229009', 'Ph: +91 80 26548271');
--
--insert into bank_account_addresses (bank_account_id, address_id) values (3, 24);
--
--insert into aishwarya_bank_accounts (bank_account_id, start_date, end_date) values (3, NOW(), '2050-01-01')