--insert into addresses (street, area, city, state, pincode) values ('No. 87/2, Muneshwara Layout, Karihobinahalli Main Road, Peenya 2nd Stage', 'Thigalarapalya', 'Bangalore', 'KA', '560058');
--insert into suppliers (name, type) values ('ARABIAN KITCHEN EQUIPMENTS', 'domestic');
--
--select * from addresses
--select * from suppliers
--
--insert into supplier_addresses (supplier_id, address_id) values (4, 27);
--
--
--insert into bank_accounts (name, branch, swift_code, account_number, iban, other_details) values ('INDIAN OVERSEAS BANK', 'PEENYA INDUSTRIAL ESTATE', 'IOBA0003746', '374602000000411', '', '');
--insert into addresses (street, area, city, state, pincode) values ('Peenya Main Road', 'Peenya', 'Bangalore', 'KA', '560094');
--
--select * from bank_accounts
--
--insert into bank_account_addresses (bank_account_id, address_id) values (4, 28)
--insert into supplier_bank_accounts (supplier_id, bank_account_id) values (4, 4)